CREATE TABLE IF NOT EXISTS Employee(
	id SERIAL PRIMARY KEY,
	name VARCHAR(60) NOT NULL,
	department_id INTEGER REFERENCES Department(id),
	head_id INTEGER NOT NULL REFERENCES Employee(id)
);

CREATE TABLE IF NOT EXISTS Department (
	id SERIAL PRIMARY KEY,
	name VARCHAR(40) UNIQUE NOT NULL
);